filter:
    excluded_paths: [test/*, res/*]



build:
    environment:
        node: 16.13.0

    nodes:
        analysis:
            tests:
                override:
                    - js-scrutinizer-run

        test-coverage:
            tests:
                before:
                    - npm install
                override:
                    - command: npm run test
                      coverage:
                        file: "coverage/clover.xml"
                        format: "clover"
